development:
  adapter: postgresql
  encoding: unicode
  database: shift_app_development
  pool: 5
  #username: cashflow
  username: michael
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: shift_app_test
  pool: 5
  #username: cashflow
  username: michael
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: shift_app_development
  pool: 5
  #username: cashflow
  username: michael
  password: 